version: "3"
services:
  app:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /bin/sh docker_dev_start.sh
    ports:
      - "8080:4000"
    depends_on:
      - db
    links:
      - db
  db:
    restart: always
    image:  postgres
    environment:
      POSTGRES_PASSWORD:  postgres
      POSTGRES_USER:  postgres
    ports:
      - "5432:5432"

