FROM elixir:alpine

RUN apk add --no-cache build-base npm git python3

WORKDIR /app

RUN mix local.hex --force && \
    mix local.rebar --force

COPY . .

RUN mix do deps.get, deps.compile

RUN echo "{}" >> ./assets/package.json \
   && npm install --prefix ./assets

COPY docker_dev_start.sh docker_dev_start.sh

EXPOSE 4000


